name: Python Boto3 expamle for AWS

on:
  workflow_dispatch:
    inputs:
      infra_env:
        description: 'Environment of infrastructure'
        required: true
        default: 'main'

jobs: 
  destroy:
    name: destroy the Bucket created before
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
    
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: "Configure AWS Credentials" 
      uses: aws-actions/configure-aws-credentials@v1
      with:
    # AWS Access Key ID. This input is required if running in the GitHub hosted environment. It is optional if running in a self-hosted environment that already has AWS credentials, for example on an EC2 instance.
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    # AWS Secret Access Key. This input is required if running in the GitHub hosted environment. It is optional if running in a self-hosted environment that already has AWS credentials, for example on an EC2 instance.
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
   # AWS Region, e.g. us-east-2, us-east-1
          aws-region:  us-east-1
   
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install boto3 
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
 
    - name: Run python files for S3 bucket
      run: |
        cd S3
        python S3_deletedata.py
        python S3_deletebucket.py 

       
